#!/usr/bin/env python3
"""Turn the .resx string tables into Rust: crates/wandur-core/src/l10n/generated.rs.

The tables live in crates/wandur-core/locale/:
- Strings*.resx: copies of the C# client's tables (same owner, same keys), so both clients share
  their wording and translations.
- Rust*.resx: strings only the Rust client has, in the same five languages.

Each language has a file per table: English is the base (Strings.resx), the others carry a
culture suffix (Strings.de.resx). Every language must have exactly the base keys.

Usage:
    python3 scripts/generate-localization.py            # write generated.rs
    python3 scripts/generate-localization.py --check    # fail if generated.rs or a table is stale
    python3 scripts/generate-localization.py --csharp DIR [--check]
        # DIR is the C# client's src/Wandur.Core/Localization: copy its Strings*.resx here first
        # (or, with --check, fail if the copies differ from it)
"""
from pathlib import Path
import argparse
import filecmp
import shutil
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
LOCALE = ROOT / 'crates/wandur-core/locale'
OUTPUT = ROOT / 'crates/wandur-core/src/l10n/generated.rs'
# The order is the Language enum's order in l10n/mod.rs.
LANGUAGES = [('en', ''), ('es', '.es'), ('fr', '.fr'), ('de', '.de'), ('pt-BR', '.pt-BR')]
TABLES = ['Strings', 'Rust']


def fail(message):
    sys.exit(message)


def read_table(path):
    if not path.exists():
        fail(f'{path.relative_to(ROOT)} is missing.')
    entries = []
    for data in ET.parse(path).findall('data'):
        value = data.find('value')
        entries.append((data.attrib['name'], '' if value is None or value.text is None else value.text))
    return entries


def rust_string(text):
    out = []
    for c in text:
        if c == '\\':
            out.append('\\\\')
        elif c == '"':
            out.append('\\"')
        elif c == '\n':
            out.append('\\n')
        elif c == '\r':
            out.append('\\r')
        elif c == '\t':
            out.append('\\t')
        elif ord(c) < 0x20 or ord(c) == 0x7f:
            out.append('\\u{%x}' % ord(c))
        else:
            out.append(c)
    return '"' + ''.join(out) + '"'


def doc_line(text):
    one = ' '.join(text.split())
    if len(one) > 90:
        one = one[:87] + '...'
    return one.replace('`', "'")


def generate():
    keys = []
    english = {}
    for table in TABLES:
        for key, value in read_table(LOCALE / f'{table}.resx'):
            keys.append(key)
            english[key] = value
    folded = [k.casefold() for k in keys]
    if len(set(folded)) != len(folded):
        dupes = sorted({k for k in keys if folded.count(k.casefold()) > 1})
        fail('Resource keys must be unique ignoring case, across tables: ' + ', '.join(dupes))
    for key in keys:
        if not key.isidentifier() or not key[0].isupper() or key == 'Self':
            fail(f'{key} is not usable as a Rust enum variant.')
    columns = []
    for code, suffix in LANGUAGES:
        values = {}
        for table in TABLES:
            path = LOCALE / f'{table}{suffix}.resx'
            entries = read_table(path)
            base = {k for k, _ in read_table(LOCALE / f'{table}.resx')}
            have = {k for k, _ in entries}
            if have != base:
                missing = sorted(base - have)
                extra = sorted(have - base)
                fail(f'{path.relative_to(ROOT)}: missing {missing[:10]} extra {extra[:10]}')
            values.update(entries)
        empty = [k for k in keys if not values[k].strip()]
        if empty:
            fail(f'{code}: empty values for {empty[:10]}')
        columns.append([values[k] for k in keys])

    lines = [
        '// Generated by scripts/generate-localization.py from crates/wandur-core/locale/*.resx.',
        '// Do not edit: change the .resx files, then run python3 scripts/generate-localization.py.',
        '',
        '/// Every UI string by its resource key (the C# client\'s key for the strings both clients share).',
        '/// The doc line of each is its English text.',
        '#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]',
        '#[repr(u16)]',
        'pub enum S {',
    ]
    for key in keys:
        lines.append(f'    /// {doc_line(english[key])}')
        lines.append(f'    {key},')
    lines.append('}')
    lines.append('')
    lines.append('/// How many strings there are.')
    lines.append(f'pub const COUNT: usize = {len(keys)};')
    lines.append('')
    lines.append('impl S {')
    lines.append('    /// Every key, in table order.')
    lines.append('    pub const ALL: [S; COUNT] = [')
    for key in keys:
        lines.append(f'        S::{key},')
    lines.append('    ];')
    lines.append('}')
    lines.append('')
    lines.append('/// The resource key names, in table order.')
    lines.append('pub static NAMES: [&str; COUNT] = [')
    for key in keys:
        lines.append(f'    "{key}",')
    lines.append('];')
    lines.append('')
    lines.append('/// The text of every key in each language, in the order of `Language`.')
    lines.append(f'pub static TABLES: [[&str; COUNT]; {len(LANGUAGES)}] = [')
    for (code, _), column in zip(LANGUAGES, columns):
        lines.append(f'    // {code}')
        lines.append('    [')
        for value in column:
            lines.append(f'        {rust_string(value)},')
        lines.append('    ],')
    lines.append('];')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='fail on drift instead of writing')
    parser.add_argument('--csharp', type=Path, help="the C# client's Localization folder")
    args = parser.parse_args()
    if args.csharp:
        for _, suffix in LANGUAGES:
            source = args.csharp / f'Strings{suffix}.resx'
            copy = LOCALE / f'Strings{suffix}.resx'
            if args.check:
                if not copy.exists() or not filecmp.cmp(source, copy, shallow=False):
                    fail(f'{copy.relative_to(ROOT)} differs from {source}. Run without --check to copy it.')
            else:
                shutil.copyfile(source, copy)
    text = generate()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8') != text:
            fail('generated.rs is out of date. Run python3 scripts/generate-localization.py.')
        print('localization tables are up to date')
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(text, encoding='utf-8')
        print(f'wrote {OUTPUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
